name: Deploy project to prod environment

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t prod
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run pipeline workflow
        run: |
          set -o pipefail
          databricks bundle run cicd_project_job -t prod --refresh-all 2>&1 | tee output.log
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod